//! Typed emit helpers from Photon Spectra schemas.
//!
//! Each type below is generated by a `spectra_schema!` / `spectra_metric!` invocation in
//! `schemas/`; the `*Logger` / `*Recorder` types are what [`crate::SpectraOpsLog`]
//! calls to emit a row or bump a counter/gauge.
//!
//! # Examples
//!
//! ```rust,no_run
//! use photon_spectra_telemetry::helpers::PhotonPublishesRecorder;
//!
//! PhotonPublishesRecorder::record(1, serde_json::json!({"topic": "demo", "mode": "local"}));
//! ```

/// Recorder for the legacy-named `continuum_append_wall_ms` `StoragePort` wall-clock gauge.
pub use crate::schemas::continuum_append_wall_ms::ContinuumAppendWallMsRecorder;
/// Recorder for the legacy-named `continuum_op_wall_ms` `StoragePort` wall-clock gauge.
pub use crate::schemas::continuum_op_wall_ms::ContinuumOpWallMsRecorder;
/// Recorder for the `photon_backlog` gauge.
pub use crate::schemas::photon_backlog::PhotonBacklogRecorder;
/// Row type and logger for the `photon_dlq` event table.
pub use crate::schemas::photon_dlq::{PhotonDlqLog, PhotonDlqLogLogger};
/// Recorder for the `photon_drains` counter.
pub use crate::schemas::photon_drains::PhotonDrainsRecorder;
/// Recorder for the `photon_handler_failures` counter.
pub use crate::schemas::photon_handler_failures::PhotonHandlerFailuresRecorder;
/// Row type and logger for the `photon_ops_log` event table.
pub use crate::schemas::photon_ops_log::{PhotonOpsLog, PhotonOpsLogLogger};
/// Recorder for the `photon_publish_errors` counter.
pub use crate::schemas::photon_publish_errors::PhotonPublishErrorsRecorder;
/// Recorder for the `photon_publishes` counter.
pub use crate::schemas::photon_publishes::PhotonPublishesRecorder;
